version: '3.8'
services:
  nestjs-starter-auth:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - PORT=3000
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/nestjs-starter-auth
      - JWT_SECRET=secret
    depends_on:
      - db
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: rexfordkode
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: touching_lives
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:

networks:
  default:
    driver: bridge
    name: nestjs-starter-auth_network
